// Regenerated by scripts/preview-compose.sh before each run. Do not edit by hand.
package dev.composepreview.host

import androidx.compose.runtime.Composable

internal val devicePreviewCallSites: Map<String, @Composable () -> Unit> = emptyMap()
