#!/usr/bin/env bash
# Render @Preview composables in a Kotlin file on an Android emulator by
# installing the debug APK and launching a bundled PreviewActivity with the
# target preview's FQN as an intent extra.
#
# Usage: preview-compose.sh <path/to/File.kt>
#
# On first invocation in a project, the required debug-source files and
# manifest are copied from the plugin's templates into app/src/debug/.
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES_ROOT="$PLUGIN_ROOT/templates"

# Hardcoded for the Punch project. Parameterize via a project config file when
# onboarding other Android repos.
GRADLE_INSTALL_TASK=":app:installProductionDebug"
DEVICE_ACTIVITY_FQN="dev.composepreview.host.PreviewActivity"
DEVICE_APPLICATION_ID="com.marketpulse.sniper.vte"
DEVICE_PACKAGE="dev.composepreview.host"
DEVICE_CALLSITES_PATH="app/src/debug/kotlin/dev/composepreview/host/DevicePreviewCallSites.kt"
PREFERRED_AVD="${PREVIEW_AVD:-tech-preview-compose}"

PREVIEW_FILE="${1:-}"
if [[ -z "$PREVIEW_FILE" || ! -f "$PREVIEW_FILE" ]]; then
  echo "Usage: $0 <path/to/File.kt>" >&2
  exit 1
fi

resolveAndroidProjectRoot() {
  local candidate="$PWD"
  while [[ "$candidate" != "/" ]]; do
    if [[ -x "$candidate/gradlew" ]]; then
      echo "$candidate"
      return 0
    fi
    candidate="$(dirname "$candidate")"
  done
  echo "no gradlew found walking up from $PWD — run this from inside an Android project" >&2
  return 1
}
PROJECT_ROOT="$(resolveAndroidProjectRoot)" || exit 1
PREVIEW_FILE_ABS="$(cd "$(dirname "$PREVIEW_FILE")" && pwd)/$(basename "$PREVIEW_FILE")"

bootstrapDebugSources() {
  local activityPath="$PROJECT_ROOT/app/src/debug/kotlin/dev/composepreview/host/PreviewActivity.kt"
  local manifestPath="$PROJECT_ROOT/app/src/debug/AndroidManifest.xml"
  local callSitesPath="$PROJECT_ROOT/$DEVICE_CALLSITES_PATH"

  if [[ ! -f "$activityPath" ]]; then
    mkdir -p "$(dirname "$activityPath")"
    cp "$TEMPLATES_ROOT/debug/kotlin/dev/composepreview/host/PreviewActivity.kt" "$activityPath"
    echo "bootstrap: wrote $activityPath"
  fi
  if [[ ! -f "$manifestPath" ]]; then
    mkdir -p "$(dirname "$manifestPath")"
    cp "$TEMPLATES_ROOT/debug/AndroidManifest.xml" "$manifestPath"
    echo "bootstrap: wrote $manifestPath"
  fi
  if [[ ! -f "$callSitesPath" ]]; then
    mkdir -p "$(dirname "$callSitesPath")"
    cp "$TEMPLATES_ROOT/debug/kotlin/dev/composepreview/host/DevicePreviewCallSites.kt" "$callSitesPath"
    echo "bootstrap: wrote $callSitesPath"
  fi
}

extractPackage() {
  grep -m1 -E '^package ' "$1" | awk '{print $2}' | tr -d ';'
}

extractDeclaringClass() {
  local file="$1"
  local jvmNameOverride
  jvmNameOverride="$(grep -m1 -E '@file:JvmName' "$file" | sed -E 's/.*@file:JvmName\("([^"]+)"\).*/\1/' || true)"
  if [[ -n "$jvmNameOverride" && "$jvmNameOverride" != *'@file:JvmName'* ]]; then
    echo "$jvmNameOverride"
    return
  fi
  local baseName
  baseName="$(basename "$file" .kt)"
  echo "$(echo "${baseName:0:1}" | tr '[:lower:]' '[:upper:]')${baseName:1}Kt"
}

extractPreviewFunctionNames() {
  awk '
    /@Preview/ { previewPending = 1 }
    previewPending && /^[[:space:]]*(private|internal|public)?[[:space:]]*fun[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\(/ {
      sig = $0
      sub(/^[[:space:]]*/, "", sig)
      visibility = "public"
      if (sig ~ /^private[[:space:]]/) { visibility = "private" }
      sub(/^(private|internal|public)?[[:space:]]*/, "", sig)
      sub(/^fun[[:space:]]+/, "", sig)
      sub(/[[:space:]]*\(.*$/, "", sig)
      if (visibility == "private") {
        printf "warning: skipping `private` @Preview %s — change to internal or public to render it\n", sig > "/dev/stderr"
      } else {
        print sig
      }
      previewPending = 0
    }
  ' "$1"
}

writeDeviceCallSites() {
  local sourcePackage="$1"
  local declaringClass="$2"
  shift 2
  local previewFunctions=( "$@" )
  local absPath="$PROJECT_ROOT/$DEVICE_CALLSITES_PATH"
  mkdir -p "$(dirname "$absPath")"
  {
    echo "// Generated by preview-compose.sh — do not edit."
    echo "package $DEVICE_PACKAGE"
    echo
    echo "import androidx.compose.runtime.Composable"
    for previewFunction in "${previewFunctions[@]}"; do
      echo "import ${sourcePackage}.${previewFunction}"
    done
    echo
    echo "internal val devicePreviewCallSites: Map<String, @Composable () -> Unit> = mapOf("
    for previewFunction in "${previewFunctions[@]}"; do
      local fqnKey="${sourcePackage}.${declaringClass}#${previewFunction}"
      echo "  \"${fqnKey}\" to @Composable { ${previewFunction}() },"
    done
    echo ")"
  } > "$absPath"
}

selectDeviceSerial() {
  local connectedDevices
  connectedDevices="$(adb devices | awk 'NR>1 && /device$/ {print $1}')"
  if [[ -z "$connectedDevices" ]]; then
    echo "No device/emulator connected. Boot it first." >&2
    return 1
  fi
  if [[ -n "${ANDROID_SERIAL:-}" ]]; then
    if printf '%s\n' "$connectedDevices" | grep -qx "$ANDROID_SERIAL"; then
      echo "$ANDROID_SERIAL"
      return 0
    fi
    echo "ANDROID_SERIAL=$ANDROID_SERIAL not attached; falling through" >&2
  fi
  local candidate avdName
  while IFS= read -r candidate; do
    avdName="$(adb -s "$candidate" emu avd name 2>/dev/null | head -1 | tr -d '\r')"
    if [[ "$avdName" == "$PREFERRED_AVD" ]]; then
      echo "$candidate"
      return 0
    fi
  done <<< "$connectedDevices"
  local fallback
  fallback="$(printf '%s\n' "$connectedDevices" | head -1)"
  echo "warning: no $PREFERRED_AVD AVD attached; using $fallback" >&2
  echo "$fallback"
}

renderOnDevice() {
  command -v adb >/dev/null || { echo "adb not on PATH" >&2; return 1; }
  local targetDevice
  targetDevice="$(selectDeviceSerial)" || return 1
  export ANDROID_SERIAL="$targetDevice"

  bootstrapDebugSources

  local sourcePackage declaringClass previewFunctionNames
  sourcePackage="$(extractPackage "$PREVIEW_FILE_ABS")"
  [[ -n "$sourcePackage" ]] || { echo "no package in $PREVIEW_FILE_ABS" >&2; return 1; }
  declaringClass="$(extractDeclaringClass "$PREVIEW_FILE_ABS")"
  previewFunctionNames="$(extractPreviewFunctionNames "$PREVIEW_FILE_ABS")"
  [[ -n "$previewFunctionNames" ]] || { echo "no @Preview in file" >&2; return 1; }

  local functionList=() firstFqn=""
  while IFS= read -r fn; do
    [[ -z "$fn" ]] && continue
    functionList+=( "$fn" )
    [[ -z "$firstFqn" ]] && firstFqn="${sourcePackage}.${declaringClass}#${fn}"
  done <<< "$previewFunctionNames"

  writeDeviceCallSites "$sourcePackage" "$declaringClass" "${functionList[@]}"

  echo "installing: $DEVICE_APPLICATION_ID (first-launch FQN=$firstFqn)"
  (
    cd "$PROJECT_ROOT"
    ./gradlew "$GRADLE_INSTALL_TASK" -q
  ) || { echo "install failed" >&2; return 1; }

  local amStartAttempt
  for amStartAttempt in 1 2 3; do
    if adb -s "$targetDevice" shell am start \
         -n "${DEVICE_APPLICATION_ID}/${DEVICE_ACTIVITY_FQN}" \
         --es preview.fqn "$firstFqn" >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done

  echo "running on $targetDevice. Additional previews in this file:"
  for fn in "${functionList[@]}"; do
    echo "  adb shell am start -n ${DEVICE_APPLICATION_ID}/${DEVICE_ACTIVITY_FQN} --es preview.fqn '${sourcePackage}.${declaringClass}#${fn}'"
  done
}

renderOnDevice
